// <auto-generated />
namespace MVC_InventoryWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202305031445155_UserModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
